Repository DarkmiraTour/community-event-manager, pull requests merged in 2018-11, with the labels that each got.

#20 [WIP] Manage speaker
  .env.dist
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/storage.yaml
  config/packages/storage.yaml
  config/routes.yaml
  config/routes/speakers.yaml
  config/services.yaml
  src/Controller/Speaker/Create.php
  src/Controller/Speaker/Delete.php
  src/Controller/Speaker/Edit.php
  src/Controller/Speaker/Index.php
  src/Controller/Speaker/Show.php
  src/DataFixtures/SpeakerFixtures.php
  src/Dto/SpeakerRequest.php
  src/Entity/Speaker.php
  src/Form/SpeakerType.php
  src/Migrations/Version20181029125024.php
  src/Repository/SpeakerRepository.php
  src/Repository/SpeakerRepositoryInterface.php
  src/Service/FileUploader.php
  src/Service/FileUploaderInterface.php
  src/Twig/StorageExtension.php
  symfony.lock
  templates/speaker/_delete_form.html.twig
  templates/speaker/create.html.twig
  templates/speaker/edit.html.twig
  templates/speaker/index.html.twig
  templates/speaker/show.html.twig
Labels: enhancement, speaker

#30 Manage Special Sponsorships
  composer.json
  composer.lock
  config/routes.yaml
  config/routes/specialBenefit.yaml
  src/Controller/SpecialBenefit/Create.php
  src/Controller/SpecialBenefit/Delete.php
  src/Controller/SpecialBenefit/Edit.php
  src/Controller/SpecialBenefit/Index.php
  src/Controller/SpecialBenefit/Show.php
  src/DataFixtures/SpecialBenefitFixtures.php
  src/Dto/SpecialBenefitRequest.php
  src/Entity/SpecialBenefit.php
  src/Form/SpecialBenefitType.php
  src/Migrations/Version20181109150434.php
  src/Repository/SpecialBenefit/SpecialBenefitManager.php
  src/Repository/SpecialBenefit/SpecialBenefitManagerInterface.php
  src/Repository/SpecialBenefit/SpecialBenefitRepository.php
  src/Repository/SpecialBenefit/SpecialBenefitRepositoryInterface.php
  templates/layout/header.html.twig
  templates/specialBenefit/_form.html.twig
  templates/specialBenefit/create.html.twig
  templates/specialBenefit/edit.html.twig
  templates/specialBenefit/index.html.twig
  templates/specialBenefit/show.html.twig
Labels: enhancement, sponsor

#29 Fix Node container errors
  docker-compose.yml
Labels: bug

#41 Create bucket at storage startup
  docker-compose.yml
  var/s3/events/.gitignore
Labels: enhancement

#44 Move docker container config in docker/
  docker-compose.yml
  docker/nginx/default.conf
  docker/php-fpm/Dockerfile
Labels: enhancement

#45 Fix organisations and speakers cruds templates
  templates/organisations/create.html.twig
  templates/organisations/edit.html.twig
  templates/organisations/list.html.twig
  templates/organisations/show.html.twig
  templates/speaker/create.html.twig
  templates/speaker/edit.html.twig
  templates/speaker/index.html.twig
  templates/speaker/show.html.twig
Labels: bug

#36 Sponsorships refactorization
  assets/js/sponsorshipLevelBenefit/edit.js
  package-lock.json
  src/Controller/SpecialBenefit/Create.php
  src/Controller/SpecialBenefit/Delete.php
  src/Controller/SpecialBenefit/Edit.php
  src/Controller/SpecialBenefit/Index.php
  src/Controller/SpecialBenefit/Show.php
  src/Controller/SponsorshipBenefit/Create.php
  src/Controller/SponsorshipBenefit/Delete.php
  src/Controller/SponsorshipBenefit/Edit.php
  src/Controller/SponsorshipBenefit/Index.php
  src/Controller/SponsorshipLevel/Create.php
  src/Controller/SponsorshipLevel/Delete.php
  src/Controller/SponsorshipLevel/Edit.php
  src/Controller/SponsorshipLevel/Index.php
  src/Controller/SponsorshipLevelBenefit/Edit.php
  src/DataFixtures/SponsorshipBenefitFixtures.php
  src/DataFixtures/SponsorshipLevelBenefitFixtures.php
  src/DataFixtures/SponsorshipLevelFixtures.php
  src/Dto/SponsorshipBenefitRequest.php
  src/Dto/SponsorshipLevelBenefitRequest.php
  src/Dto/SponsorshipLevelRequest.php
  src/Entity/SpecialBenefit.php
  src/Entity/SponsorshipBenefit.php
  src/Entity/SponsorshipLevel.php
  src/Entity/SponsorshipLevelBenefit.php
  src/Form/SpecialBenefitType.php
  src/Form/SponsorshipBenefitType.php
  src/Form/SponsorshipLevelType.php
  src/Migrations/Version20181107143554.php
  src/Migrations/Version20181109150434.php
  src/Repository/SpecialBenefit/SpecialBenefitManager.php
  src/Repository/SpecialBenefit/SpecialBenefitManagerInterface.php
  src/Repository/SpecialBenefit/SpecialBenefitRepository.php
  src/Repository/SpecialBenefit/SpecialBenefitRepositoryInterface.php
  src/Repository/SponsorshipBenefit/SponsorshipBenefitManager.php
  src/Repository/SponsorshipBenefit/SponsorshipBenefitManagerInterface.php
  src/Repository/SponsorshipBenefit/SponsorshipBenefitRepository.php
  src/Repository/SponsorshipBenefit/SponsorshipBenefitRepositoryInterface.php
  src/Repository/SponsorshipLevel/SponsorshipLevelManager.php
  src/Repository/SponsorshipLevel/SponsorshipLevelManagerInterface.php
  src/Repository/SponsorshipLevel/SponsorshipLevelRepository.php
  src/Repository/SponsorshipLevel/SponsorshipLevelRepositoryInterface.php
  src/Repository/SponsorshipLevelBenefit/SponsorshipLevelBenefitManager.php
  src/Repository/SponsorshipLevelBenefit/SponsorshipLevelBenefitManagerInterface.php
  src/Repository/SponsorshipLevelBenefit/SponsorshipLevelBenefitRepository.php
  src/Repository/SponsorshipLevelBenefit/SponsorshipLevelBenefitRepositoryInterface.php
  templates/sponsorshipLevelBenefit/edit.html.twig
Labels: enhancement
