Repository DarkmiraTour/community-event-manager, pull requests merged in 2018-12, with the labels that each got.

#52 Add currency symbol
  composer.json
  composer.lock
  config/packages/twig.yaml
  config/packages/twig_extensions.yaml
  config/services.yaml
  src/DataFixtures/SponsorshipLevelFixtures.php
  src/Form/SpecialBenefitType.php
  src/Form/SponsorshipLevelType.php
  symfony.lock
  templates/specialBenefit/index.html.twig
  templates/specialBenefit/show.html.twig
  templates/sponsorshipLevel/index.html.twig
  templates/sponsorshipLevelBenefit/view.html.twig
Labels: enhancement

#34 Authentication user with login form
  .php_cs.dist
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/routes.yaml
  config/routes/login.yaml
  src/Controller/Login/Security.php
  src/Controller/Login/SignInSuccessful.php
  src/DataFixtures/UserFixture.php
  src/Entity/User.php
  src/Exceptions/EmptyPlainPasswordException.php
  src/Exceptions/InvalidTypeArgumentException.php
  src/Exceptions/NotSupportedFunctionException.php
  src/Form/LoginType.php
  src/Migrations/Version20181121130537.php
  src/Repository/User/UserManager.php
  src/Repository/User/UserManagerInterface.php
  src/Repository/User/UserRepository.php
  src/Repository/User/UserRepositoryFactory.php
  src/Repository/User/UserRepositoryInterface.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/layout/header.html.twig
  templates/organisations/show.html.twig
  templates/security/login.html.twig
  templates/security/login_successful.html.twig
  templates/speaker/show.html.twig
  templates/specialBenefit/index.html.twig
  templates/specialBenefit/show.html.twig
  templates/sponsorshipBenefit/index.html.twig
  templates/sponsorshipLevel/index.html.twig
  templates/sponsorshipLevelBenefit/view.html.twig
Labels: enhancement, good first issue, user

#62 Fix user table name to match with linked entity User
  src/Migrations/Version20181121130537.php
Labels: bug

#65 Upgrade to PHP 7.3
  .travis.yml
  composer.json
  composer.lock
  docker/php-fpm/Dockerfile
  symfony.lock
Labels: enhancement

#68 Clean menu
  templates/layout/header.html.twig
Labels: enhancement

#26 Manage Schedule and Activities
  config/routes.yaml
  config/routes/schedule.yaml
  src/Controller/Schedule/Create.php
  src/Controller/Schedule/Delete.php
  src/Controller/Schedule/Index.php
  src/Controller/Slot/Create.php
  src/Controller/Slot/Delete.php
  src/Controller/Slot/Edit.php
  src/Controller/Space/Create.php
  src/Controller/Space/Delete.php
  src/DataFixtures/ScheduleFixtures.php
  src/DataFixtures/SlotTypeFixtures.php
  src/DataFixtures/SpaceTypeFixtures.php
  src/Dto/ScheduleRequest.php
  src/Dto/SlotRequest.php
  src/Dto/SlotTypeRequest.php
  src/Dto/SpaceRequest.php
  src/Entity/Schedule.php
  src/Entity/Slot.php
  src/Entity/SlotType.php
  src/Entity/Space.php
  src/Entity/SpaceType.php
  src/Form/ScheduleType.php
  src/Form/SlotType.php
  src/Form/SpaceType.php
  src/Migrations/Version20181129133023.php
  src/Repository/Schedule/ScheduleRepository.php
  src/Repository/Schedule/ScheduleRepositoryInterface.php
  src/Repository/Schedule/SlotRepository.php
  src/Repository/Schedule/SlotRepositoryInterface.php
  src/Repository/Schedule/SlotTypeRepository.php
  src/Repository/Schedule/SlotTypeRepositoryInterface.php
  src/Repository/Schedule/SpaceRepository.php
  src/Repository/Schedule/SpaceRepositoryInterface.php
  src/Repository/Schedule/SpaceTypeRepository.php
  src/Repository/Schedule/SpaceTypeRepositoryInterface.php
  src/Service/Schedule/CreateDailySchedule.php
  templates/layout/header.html.twig
  templates/schedule/create.html.twig
  templates/schedule/index.html.twig
  templates/schedule/slot/edit.html.twig
Labels: enhancement, talk

#60 Test sponsorships
  .gitignore
  .travis.yml
  Makefile
  behat.yml.dist
  composer.json
  composer.lock
  config/bootstrap.php
  docker-compose.yml
  features/bootstrap/FeatureContext.php
  features/bootstrap/SponsorshipContext.php
  features/bootstrap/bootstrap.php
  features/sponsorshipBenefit.feature
  features/sponsorshipLevel.feature
  features/sponsorshipLevelBenefit.feature
  src/DataFixtures/SponsorshipBenefitFixtures.php
  src/DataFixtures/SponsorshipLevelBenefitFixtures.php
  src/Dto/SponsorshipBenefitRequest.php
  src/Dto/SponsorshipLevelRequest.php
  src/Form/SponsorshipBenefitType.php
  src/Form/SponsorshipLevelType.php
  symfony.lock
  templates/sponsorshipBenefit/_form.html.twig
  templates/sponsorshipBenefit/index.html.twig
  templates/sponsorshipLevel/_form.html.twig
  templates/sponsorshipLevel/index.html.twig
Labels: enhancement

#67 Optimize travis execution time
  .travis.yml
Labels: enhancement

#71 Clean templates
  assets/css/base.scss
  features/bootstrap/FeatureContext.php
  features/page.feature
  features/sponsorshipBenefit.feature
  features/sponsorshipLevel.feature
  templates/base.html.twig
  templates/layout/header.html.twig
  templates/organisations/create.html.twig
  templates/organisations/edit.html.twig
  templates/organisations/list.html.twig
  templates/organisations/show.html.twig
  templates/page/_delete_form.html.twig
  templates/page/_form.html.twig
  templates/page/create.html.twig
  templates/page/edit.html.twig
  templates/page/index.html.twig
  templates/page/show.html.twig
  templates/schedule/configure/_day.html.twig
  templates/schedule/configure/_delete_day.html.twig
  templates/schedule/configure/_delete_slot.html.twig
  templates/schedule/configure/_delete_space.html.twig
  templates/schedule/create.html.twig
  templates/schedule/index.html.twig
  templates/schedule/modal/_add_day.html.twig
  templates/schedule/modal/_add_slot.html.twig
  templates/schedule/modal/_add_space.html.twig
  templates/schedule/slot/edit.html.twig
  templates/speaker/create.html.twig
  templates/speaker/edit.html.twig
  templates/speaker/index.html.twig
  templates/speaker/show.html.twig
  templates/specialBenefit/_delete_form.html.twig
  templates/specialBenefit/_form.html.twig
  templates/specialBenefit/create.html.twig
  templates/specialBenefit/edit.html.twig
  templates/specialBenefit/index.html.twig
  templates/specialBenefit/show.html.twig
  templates/sponsorshipBenefit/_delete_form.html.twig
  templates/sponsorshipBenefit/_form.html.twig
  templates/sponsorshipBenefit/create.html.twig
  templates/sponsorshipBenefit/edit.html.twig
  templates/sponsorshipBenefit/index.html.twig
  templates/sponsorshipLevel/_delete_form.html.twig
  templates/sponsorshipLevel/_form.html.twig
  templates/sponsorshipLevel/create.html.twig
  templates/sponsorshipLevel/edit.html.twig
  templates/sponsorshipLevel/index.html.twig
  templates/sponsorshipLevelBenefit/edit.html.twig
  templates/sponsorshipLevelBenefit/view.html.twig
  templates/talks/create.html.twig
  templates/talks/edit.html.twig
  templates/talks/index.html.twig
  templates/talks/show.html.twig
Labels: bug, enhancement
