Repository DarkmiraTour/community-event-manager, pull requests merged in 2019-03, with the labels that each got.

#94 add pull request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#93 Add contributing policies
  CHANGELOG.md
  CONTRIBUTING.md
Labels: enhancement

#108 Add confirmation page to Delete actions in organisation
  config/routes/organisations.yaml
  src/Controller/Organisation/DeleteConfirmation.php
  templates/organisations/_delete_form.html.twig
  templates/organisations/confirm_delete.html.twig
  templates/organisations/list.html.twig
  templates/organisations/show.html.twig
Labels: enhancement, user

#125 fixes #112 - add Behat test suite into make test command
  Makefile
Labels: enhancement, good first issue
