Repository DarkmiraTour/community-event-manager, pull requests merged in 2019-10, with the labels that each got.

#218 hide title field on slot form when slot type is talk
  assets/js/schedule/slot/add_slot.js
  assets/js/schedule/slot/edit_slot.js
Labels: enhancement

#171 [Fixes #170] Add an organization data import in csv format
  assets/js/organisation/upload_organisation.js
  composer.json
  composer.lock
  config/routes/organisations.yaml
  config/services.yaml
  src/Controller/Organisation/Upload.php
  src/Dto/OrganisationCsvUploadRequest.php
  src/Event/Organisation/OrganisationImportEvent.php
  src/EventListener/OrganisationImportListener.php
  src/Form/OrganisationCsvUploadType.php
  src/Service/Organisation/FileCsvUploader.php
  src/Service/Organisation/FileCsvUploaderInterface.php
  symfony.lock
  templates/organisations/list.html.twig
  templates/organisations/upload.html.twig
  webpack.config.js
Labels: enhancement

#220 Change back button redirection back to list
  templates/organisations/upload.html.twig
Labels: bug

#229 Remove duplication knp-paginator in symfony.lock
  symfony.lock
Labels: Hacktoberfest, good first issue

#227 Add HTTP constants in the controllers
  src/Controller/InterviewQuestion/Edit.php
  src/Controller/Organisation/Edit.php
  src/Controller/Page/Edit.php
  src/Controller/SlotType/Edit.php
  src/Controller/SpecialBenefit/Edit.php
  src/Controller/SponsorshipBenefit/Edit.php
  src/Controller/SponsorshipLevel/Edit.php
Labels: Hacktoberfest, good first issue

#211 feature oriented architecture
  config/routes.yaml
  config/routes/talks.yaml
  features/bootstrap/TalkContext.php
  features/talk.feature
  src/Action.php
  src/Controller/Speaker/UploadFromOpenCfp.php
  src/Dto/SlotRequest.php
  src/Entity/Slot.php
  src/Entity/Speaker.php
  src/Form/SlotType.php
  src/Kernel.php
  src/Repository/Schedule/SlotRepository.php
  src/Repository/TalkRepositoryInterface.php
  src/Service/UploadFromOpenCFP/UploadedCsvCreateSpeakerTalk.php
  src/Talk/Create/CreateTalkAction.php
  src/Talk/Create/CreateTalkFormType.php
  src/Talk/Create/CreateTalkRequest.php
  src/Talk/Create/TalkFactory.php
  src/Talk/Delete/DeleteTalkAction.php
  src/Talk/Delete/DeleteTalkConfirmationAction.php
  src/Talk/Doctrine/TalkFixtures.php
  src/Talk/Doctrine/TalkRepository.php
  src/Talk/Index/IndexAction.php
  src/Talk/Resources/config/doctrine/Talk.orm.xml
  src/Talk/Resources/config/packages/doctrine.yaml
  src/Talk/Resources/config/routes.yaml
  src/Talk/Resources/config/routes/talks.yaml
  src/Talk/Resources/config/services.yaml
  src/Talk/Show/ShowTalkAction.php
  src/Talk/Talk.php
  src/Talk/TalkRepositoryInterface.php
  src/Talk/Update/UpdateTalkAction.php
  src/Talk/Update/UpdateTalkFormType.php
  src/Talk/Update/UpdateTalkRequest.php
Labels: PR open, enhancement

#212 Monolog is only required in dev dependencies
  config/bundles.php
Labels: bug
